jQuery(document).ready(function(){
  jQuery('.quickview').click(function(e){
    e.preventDefault();
    jQuery('body').addClass('quickview-open');
  });
  jQuery('.close-quickview').click(function(f){
    f.preventDefault();
    jQuery('body').removeClass('quickview-open');
  });
});